
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace HotUpdate.DataTable
{
public partial class Tables
{
    public Config.TbItem TbItem {get; }
    public Store.TbStoreItem TbStoreItem {get; }
    public Player.TbInventory TbInventory {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbItem = new Config.TbItem(loader("config_tbitem"));
        TbStoreItem = new Store.TbStoreItem(loader("store_tbstoreitem"));
        TbInventory = new Player.TbInventory(loader("player_tbinventory"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbStoreItem.ResolveRef(this);
        TbInventory.ResolveRef(this);
    }
}

}
