
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace HotUpdate.DataTable.Config
{
public partial class TbItem
{
    private readonly System.Collections.Generic.Dictionary<int, Config.Item> _dataMap;
    private readonly System.Collections.Generic.List<Config.Item> _dataList;
    
    public TbItem(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Config.Item>(count);
        _dataList = new System.Collections.Generic.List<Config.Item>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Config.Item _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = HotUpdate.DataTable.Config.Item.DeserializeItem(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Config.Item> DataMap => _dataMap;
    public System.Collections.Generic.List<Config.Item> DataList => _dataList;

    public Config.Item GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Config.Item Get(int key) => _dataMap[key];
    public Config.Item this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

