
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace HotUpdate.DataTable.Player
{
public sealed partial class Inventory : Luban.BeanBase
{
    public Inventory(JSONNode _buf) 
    {
        { if(!_buf["item_id"].IsNumber) { throw new SerializationException(); }  ItemId = _buf["item_id"]; }
        { if(!_buf["count"].IsNumber) { throw new SerializationException(); }  Count = _buf["count"]; }
    }

    public static Inventory DeserializeInventory(JSONNode _buf)
    {
        return new Player.Inventory(_buf);
    }

    /// <summary>
    /// 道具id
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Count;
   
    public const int __ID__ = -230685041;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "itemId:" + ItemId + ","
        + "count:" + Count + ","
        + "}";
    }
}
}

