
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace HotUpdate.DataTable.Player
{
public partial class TbInventory
{
    private readonly System.Collections.Generic.Dictionary<int, Player.Inventory> _dataMap;
    private readonly System.Collections.Generic.List<Player.Inventory> _dataList;
    
    public TbInventory(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Player.Inventory>(count);
        _dataList = new System.Collections.Generic.List<Player.Inventory>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Player.Inventory _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = HotUpdate.DataTable.Player.Inventory.DeserializeInventory(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Player.Inventory> DataMap => _dataMap;
    public System.Collections.Generic.List<Player.Inventory> DataList => _dataList;

    public Player.Inventory GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Player.Inventory Get(int key) => _dataMap[key];
    public Player.Inventory this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

