
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace HotUpdate.DataTable.Store
{
public partial class TbStoreItem
{
    private readonly System.Collections.Generic.Dictionary<int, Store.StoreItem> _dataMap;
    private readonly System.Collections.Generic.List<Store.StoreItem> _dataList;
    
    public TbStoreItem(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Store.StoreItem>(count);
        _dataList = new System.Collections.Generic.List<Store.StoreItem>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Store.StoreItem _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = HotUpdate.DataTable.Store.StoreItem.DeserializeStoreItem(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Store.StoreItem> DataMap => _dataMap;
    public System.Collections.Generic.List<Store.StoreItem> DataList => _dataList;

    public Store.StoreItem GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Store.StoreItem Get(int key) => _dataMap[key];
    public Store.StoreItem this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

